baseURL = "https://candidette.com/"
languageCode = "en-us"
title = "Candidette Campaigns"
theme = "papermod"

[params]
  description = "Campaign management for first-time candidates who are women or have non-dominant identities. Based in Seattle."
  author = "Liz"
  ShowShareButtons = false
  ShowReadingTime = false
  disableHLJS = true
  disableSpecial1stPost = true
  defaultTheme = "light"
  disableThemeToggle = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "How I Work"
    url = "/how-i-work/"
    weight = 20
  [[menu.main]]
    name = "Let's Talk"
    url = "/contact/"
    weight = 30
